config/routes.rb
Rails.application.routes.draw do





	# static routes
	get 'statistics' => 'simple#statistics', as: :statistics
	get 'downloads' => 'simple#downloads', as: :downloads
	get 'contact'  => 'simple#contact', as: :contact
	get 'citation' => 'simple#citation', as: :cite
	get 'about' => 'simple#about', as: :about
	get 'other_database' => 'simple#other_database', as: :other_database
	get 'help' => 'simple#help', as: :help
	get 'home' => 'simple#home', as: :home


	# download route
	get "simple/download_aa_original"
	get "simple/download_nt_original"
	get "simple/download_aa_cus"
	get "simple/download_nt_cus"
	get "simple/download_entry_table_nt_orignal_docx"
	get "simple/download_entry_table_cus"
	get "query/download_new_fasta"
	get "protein/download_filtered_result"
	get "protein/download_filtered_result_fasta"



	match "search" => 'query#search',
		as: :search,
		via: [:get, :post]

	match "result" => 'query#result',
		as: :result,
		via: [:get, :post]

	match "phylogenetic_tree" => 'query#phylogenies',
		as: :phylogenetic_tree,
		via: [:post]

	match "submit_sequence" => "submit_sequence#submit",
		as: :submit_sequence,
		via: [:get, :post]

	match "phylogeny" => "phylogeny#show",
		as: :phylogeny,
		via: [:get, :post]


	resources :protein, only: [:show, :index] do
	end

	resources :compound, only: [:show, :index] do 
	end


	root to: 'simple#home'

end

app/models/compound.rb
class Compound < ApplicationRecord




	before_validation :increment_public_id, on: :create
  # to attach file => Compound.image.attach(io: File.open('/path/to/file'), filename: 'file.pdf')
  has_one_attached :image


	private

  # Set the public ID to the next available ID based on the compound entries 
  # that already exist. This runs pre-validation, and only sets the public ID
  # if it hasn't been set explicitely.
  def increment_public_id
    if self.public_id.blank?
      self.public_id = Compound.exists? ? Compound.order(:public_id).last.public_id.next : 'RDDB00001'
    end
  end
end

app/controllers/compound_controller.rb
class CompoundController < ApplicationController

  helper CompoundHelper
	def index
		if params[:commit].present?
  		if params[:name].present? && !params[:header].present? && !params[:group].present? && !params[:organism].present?
  			@compound = Compound.where("name like ? ", "%#{params[:name]}%").limit(25).page(params[:page])
  		else
  			@compound = Compound.limit(15).page(params[:page])
  		end

  	else
  		@compound = Compound.limit(15).page(params[:page])
  	end

	end

	def show
		@compound = Compound.find(params[:id])
    # @synonyms = CompoundSynonym.find(params[:id])
    @protein = Array.new
    associated_protein = CompoundStrainRel.where(:compound_id => params[:id])
    associated_protein.each do |pro|
      @protein << CustomizedProteinSequence.find(pro.protein_id)
    end
	end
end

app/helpers/compound_helper.rb
module CompoundHelper

	def show_header(title, object, colspan=2)
	  name = title.gsub(/\W/, '_').downcase
	  "<tr id=\"#{name}\"><th class=\"divider\" colspan=\"#{colspan}\">#{title}</th></tr>".html_safe
	end

	def bio_link_out(site, id, name=nil, html_options=nil)
		name ||= "#{id}"

		if id.present?
			bio_link_to(name.html_safe, bio_url(site, id), html_options)
		end
	end

	def bio_link_to(name = "", options = nil, html_options = nil, &block)
	  html_options ||= {}

	  html_options[:target] ||= '_blank'

	  html_options[:class] ||= ''
	  html_options[:class] << ' wishart-link-out'
	  html_options[:class].strip!

	  link_to "#{name} #{glyphicon('new-window')}".html_safe,
	    options, html_options, &block
	end

	def nah(value=nil, message="Not Available")
	  if value.present?
	    value.to_s.html_safe
	  else
	    "<span class='wishart wishart-not-available'>#{message}</span>".html_safe
	  end
	end

	def table_header_divider(title, options={}, &block)
      options[:colspan] ||= 2
      options[:id] ||= title.to_s.parameterize

      content_tag(:tr, id: options[:id]) do
        content_tag(:th, class: 'divider', colspan: options[:colspan]) do
          block_given? ? block.call : title
        end
      end
    end

	def bio_url(site, id)
	  case site.to_sym
	    when :pubchem_compound             then "http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid=#{id}"
	    when :pubchem_cid                  then "http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid=#{id}"
	    when :pubchem_substance            then "http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?sid=#{id}"
	    when :kegg_compound                then "http://www.genome.jp/dbget-bin/www_bget?cpd:#{id}"
	    when :kegg_drug                    then "http://www.genome.jp/dbget-bin/www_bget?drug:#{id}"
	    when :kegg_pathway                 then "http://www.genome.jp/kegg/pathway/map/#{id}.html"
	    when :kegg_reaction                then "http://www.genome.jp/dbget-bin/www_bget?rn:#{id}"
	    when :kegg_gene                    then "http://www.genome.jp/dbget-bin/www_bget?eco:#{id}"
	    when :kegg_map                     then "http://www.genome.jp/kegg/pathway/map/#{id}.html"
	    when :kegg_map_thumb               then "http://www.genome.jp/kegg/misc/thumbnail/map#{id.sub(/^\D*/, '')}.gif"
	    when :chebi                        then "http://www.ebi.ac.uk/chebi/searchId.do?chebiId=#{id}"
	    when :chembl                       then "http://www.ebi.ac.uk/chembldb/index.php/compound/inspect/#{id}"
	    when :uniprot                      then "http://www.uniprot.org/uniprot/#{id}"
	    when :genbank                      then "http://www.ncbi.nlm.nih.gov/entrez/viewer.fcgi?val=#{id}"
	    when :het                          then "http://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/#{id}"
	    when :wikipedia                    then "http://en.wikipedia.org/wiki/#{id}"
	    when :wiki                         then "http://en.wikipedia.org/wiki/#{id}"
	    when :pdb                          then "http://www.rcsb.org/pdb/explore.do?structureId=#{id}"
	    when :pdb_ligand                   then "http://www.rcsb.org/pdb/ligand/ligandsummary.do?hetId=#{id}"
	    when :hgnc                         then "http://www.genenames.org/data/hgnc_data.php?hgnc_id=#{id}"
	    when :genecard                     then "http://www.genecards.org/cgi-bin/carddisp.pl?gene=#{id}"
	    when :genatlas                     then "http://www.dsi.univ-paris5.fr/genatlas/fiche1.php?symbol=#{id}"
	    when :pubmed                       then "http://www.ncbi.nlm.nih.gov/pubmed/#{id}"
	    when :drugbank                     then "http://www.drugbank.ca/drugs/#{id}"
	    when :drugbank_metabolite          then "http://www.drugbank.ca/metabolites/#{id}"
	    when :hmdb                         then "http://www.hmdb.ca/metabolites/#{id}"
	    when :chemspider                   then "http://www.chemspider.com/Chemical-Structure.#{id}.html"
	    when :bindingdb                    then "http://www.bindingdb.org/bind/chemsearch/marvin/MolStructure.jsp?monomerid=#{id}"
	    when :stitch                       then "http://stitch-db.org/interactions/#{id}"
	    when :snpjam                       then "http://snpjam.wishartlab.com/genes/#{id}"
	    when :pfam                         then "http://pfam.sanger.ac.uk/family?acc=#{id}"
	    when :dbsnp                        then "http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?rs=#{id}"
	    when :biocyc                       then "http://biocyc.org/META/NEW-IMAGE?type=COMPOUND&object=#{id}"
	    when :ecocyc                       then "http://biocyc.org/ecoli/new-image?object=#{id}"
	    when :bigg                         then "http://bigg1.ucsd.edu/bigg/view3.pl?type=metabolite&id=#{id}&model=1461534,2795088,3277493,3409217,3307911,222668,1823466,3473243,2423527,2247625"
	    when :nugo                         then "http://www.nugowiki.org/index.php/#{id}"
	    when :metagene                     then "http://www.metagene.de/program/d.prg?Accession_No=#{id}"
	    when :omim                         then "http://omim.org/entry/#{id}"
	    when :phenol_metabolite            then "http://www.phenol-explorer.eu/metabolites/#{id}"
	    when :phenol_compound              then "http://www.phenol-explorer.eu/compounds/#{id}"
	    when :foodb                        then "http://foodb.ca/" #fix when foodb goes public
	    when :foodb_compound               then "http://foodb.ca/compounds/#{id}"
	    when :afcdb_compound               then "http://afcdb.ca/compounds/#{id}"
	    when :knapsack                     then "http://kanaya.naist.jp/knapsack_jsp/result.jsp?sname=all&word=#{id}"
	    when :metlin                       then "http://metlin.scripps.edu/metabo_info.php?molid=#{id}"
	    when :golm                         then "http://gmd.mpimp-golm.mpg.de/Analytes/#{id}.aspx"
	    when :open_isbn                    then "http://www.openisbn.com/isbn/#{id}"
	    when :textbook                     then "http://www.google.com/search?tbo=p&tbm=bks&q=#{id}"
	    when :ttd                          then "http://bidd.nus.edu.sg/group/cjttd/ZFTTDDRUG.asp?ID=#{id}"
	    when :pharmgkb                     then "http://www.pharmgkb.org/drug/#{id}"
	    when :dpd                          then "http://webprod5.hc-sc.gc.ca/dpd-bdpp/info.do?code=#{id}&lang=eng"
	    when :rxlist                       then "#{id}"
	    when :pdrhealth                    then "#{id}"
	    when :drugs_dot_com                then "#{id}"
	    when :dailymed                     then "http://dailymed.nlm.nih.gov/dailymed/lookup.cfm?ndc=#{id}"
	    when :iuphar_ligand                then "http://www.iuphar-db.org/DATABASE/LigandDisplayForward?ligandId=#{id}"
	    when :guide_to_pharma_ligand       then "http://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=#{id}"
	    when :iuphar_protein               then "http://www.iuphar-db.org/DATABASE/ObjectDisplayForward?objectId=#{id}"
	    when :guide_to_pharma_protein      then "http://www.guidetopharmacology.org/GRAC/FamilyDisplayForward?familyId=#{id}"
	    when :google_patent_search         then "https://www.google.com/?tbm=pts#q=#{id}&tbm=pts"
	    when :google_patent                then "https://patents.google.com/patent/#{id}"
	    when :dfcd                         then "http://www.foodcomp.dk/v7/fcdb_details.asp?FoodId=#{id}"
	    when :ecocyc_pathway               then "http://ecocyc.org/ECOLI/NEW-IMAGE?type=PATHWAY&object=#{id}"
	    when :ecocyc_pathway_thumb         then "http://ecocyc.org/tmp/ptools-images/ECOLI/#{id}_PWY-DIAGRAM.gif"
	    when :ecocyc_compound              then "http://ecocyc.org/ECOLI/NEW-IMAGE?type=COMPOUND&object=#{id}"
	    when :ligand_expo                  then "http://ligand-expo.rcsb.org/reports/2/#{id}/index.html"
	    when :ccdb                         then "http://ccdb.wishartlab.com/CCDB/cgi-bin/ECARD_HTML_NEW.cgi?ECARD=#{id}.ecard&Coli+Card=ColiCard"
	    when :brenda                       then "http://www.brenda-enzymes.info/php/result_flat.php4?ecno=#{id}&Suchword=&organism%5B%5D=Escherichia+coli&show_tm=0"
	    when :ecogene                      then "http://www.ecogene.org/geneInfo.php?eg_id=#{id}"
	    when :colibase                     then "http://www.xbase.ac.uk/genome/escherichia-coli-str-k-12-substr-mg1655/NC_000913/#{id};thrL/viewer"
	    when :ecobase                      then "http://www.york.ac.uk/res/thomas/Gene.cfm?recordID=#{id}"
	    when :bacmap                       then "http://bacmap.wishartlab.com/cgi/getGeneCard.cgi?accession=NC_000913&id=#{id}"
	    when :ctd                          then "http://ctdbase.org/detail.go?type=chem&acc=#{id}"
	    when :ncbi_protein                 then "http://www.ncbi.nlm.nih.gov/protein/#{id}"
	    when :ncbi_cdna                    then "http://www.ncbi.nlm.nih.gov/nuccore/#{id}"
	    when :ncbi_gene                    then "http://www.ncbi.nlm.nih.gov/gene/#{id}"
	    when :dfc                          then "http://ccd.chemnetbase.com/AAA00.entry?parentCHNumber=#{id}"
	    when :duke, :duke_nutrient         then "http://sun.ars-grin.gov:8080/npgspub/xsql/duke/chemdisp.xsql?chemical=#{id}"
	    when :knapsack, :knapsack_nutrient then "http://kanaya.naist.jp/knapsack_jsp/information.jsp?word=#{id}"
	    when :eafus                        then "http://www.accessdata.fda.gov/scripts/fcn/fcnDetailNavigation.cfm?rpt=eafusListing&id=#{id}"
	    when :flavornet                    then "http://www.flavornet.org/info/#{id}.html"
	    when :goodscent                    then "http://www.thegoodscentscompany.com/data/#{id}.html"
	    when :superscent                   then "http://bioinf-applied.charite.de/superscent/src/fullinfo.php?cas=#{id}"
	    when :itis                         then "http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=#{id}"
	    when :pathwhiz                     then "http://smpdb.ca/pathwhiz/pathways/#{id}"

app/views/compound/_compound_show.html.slim
table.compound-table.content-table.table-condensed
  tbody

    = show_header 'Chemical Information', compound

    tr
      th Compound Name
      td: strong = compound.name
    tr
      th Primary ID
      td: strong = compound.public_id

    tr
      th Description
      td = nah compound.description
    tr
      th CAS Number
      td = nah compound.cas_number
    tr
      th Structure
      td
        - if compound.image.attached?
          = image_tag(compound.image)
        - else
          = image_tag("Photo-Not-Available-Image.jpg", :style => "width:130px;height:130px;")
    tr
      th Chemical Formula
      td = nah compound.formula
    tr
      th IUPAC name
      td = nah compound.iupac
    tr
      th InChI Identifier
      td = nah compound.inchi
    tr
      th InChI Key
      td = nah compound.inchikey
    tr
      th SMILES
      td = nah compound.smiles
    tr
      th Average Molecular Weight
      td = nah compound.average_mass
    tr
      th Monoisotopic Molecular Weight
      td = nah compound.mono_mass
    // NaturalProduct.update_all("np_mrd_id = REPLACE(np_mrd_id, 'HMDB', 'HMDB00')")

    / = show_header 'Physico-Chemical Properties - Experimental', compound
    / tr
    /   th Physico-Chemical Properties - Experimental
    /   td
    /     table.display.simple-datatable
    /       thead
    /         tr
    /           th Property
    /           th Value
    /           th Reference
    /       tbody
    /         tr
    /           th Physical state
    /           td = nah compound.state
    /           td = 
    /         tr
    /           th Physical Description
    /           td = nah compound.physical_description
    /           td = compound.physical_description_reference
    /         tr
    /           th Mass Composition
    /           td = nah compound.percent_composition
    /           td = compound.percent_composition_reference
    /         tr
    /           th Melting Point
    /           td = nah compound.melting_point
    /           td = compound.melting_point_reference
    /         tr
    /           th Boiling Point
    /           td = nah compound.boiling_point
    /           td = compound.boiling_point_reference
    /         tr
    /           th Experimental Water Solubility
    /           td = nah compound.experimental_solubility
    /           td = compound.experimental_solubility_reference
    /         tr
    /           th Experimental logP
    /           td = nah compound.experimental_logp
    /           td = compound.experimental_logp_reference
    /         tr
    /           th Experimental pKa
    /           td = nah compound.experimental_pka
    /           td = compound.experimental_pka_reference
    /         tr
    /           th Charge
    /           td = nah compound.charge
    /           td = compound.charge_reference
    /         tr
    /           th Optical Rotation
    /           td = nah compound.optical_rotation
    /           td = compound.optical_rotation_reference
    /         tr
    /           th Spectroscopic UV Data
    /           td = nah compound.uv_index
    /           td = compound.uv_index_reference
    /         tr
    /           th Density
    /           td = nah compound.density
    /           td = compound.density_reference
    /         tr
    /           th Refractive Index
    /           td = nah compound.refractive_index
    /           td = compound.refractive_index_reference

    = show_header 'External Links', compound
    / tr
    /   th ChemSpider ID
    /   td = nah bio_link_out :chemspider, compound.chemspider_id
    / tr
    /   th ChEMBL ID
    /   td = nah bio_link_out :chembl, compound.chembl_id
    tr
      th KEGG Compound ID
      td = nah bio_link_out :kegg_compound, compound.kegg_compound_id
    tr
      th Pubchem Compound ID
      td = nah bio_link_out :pubchem_compound, compound.pubchem_compound_id
    tr
      th Pubchem Substance ID
      td = nah bio_link_out :pubchem_substance, compound.pubchem_substance_id
    tr
      th ChEBI ID
      td = nah bio_link_out :chebi, compound.chebi_id
    tr
      th Phenol-Explorer ID
      td = nah bio_link_out :phenol_compound, compound.phenolexplorer_id
    tr
      th DrugBank ID
      td = nah bio_link_out :drugbank, compound.drugbank_id
    tr
      th HMDB ID
      td = nah bio_link_out :hmdb, compound.hmdb_id
    / tr
    /   th CRC / DFC (Dictionary of Food Compounds) ID
    /   td = nah bio_link_out :dfc, compound.dfc_id
    / tr
    /   th EAFUS ID
    /   td = nah bio_link_out :eafus, compound.eafus_id
    / tr
    /   th BIGG ID
    /   td = nah bio_link_out :bigg, compound.bigg_id
    / tr
    /   th KNApSAcK ID
    /   td = nah bio_link_out :knapsack, compound.knapsack_id
    / tr
    /   th HET ID
    /   td = nah bio_link_out :het, compound.het_id

    = show_header 'Associated Sequence', compound
    table

      .well-panel
        - if @protein.length > 0
          - @protein.each do |prot|
            = render :partial => 'protein_card', :locals => { :protein => prot}
        - else
          p Not Available

app/views/compound/_properties_table.html.slim
table class="table table-bordered"
  col width = "250"
  col width = "250"
  col width = "500"
  thead
    tr
      th Property
      th Value
      th Source
  tbody
    - if record.respond_to?(:alogps_solubility) && !record.alogps_solubility.nil?
      tr
        td Water Solubility
        td= record.alogps_solubility.to_f.smart_round_to_s + " g/L"
        td= bio_link_to_source :alogps
    - if record.respond_to?(:alogps_logp) && !record.alogps_logp.nil?
      tr
        td logP
        td= record.alogps_logp.to_f.smart_round_to_s
        td= bio_link_to_source :alogps
    - if record.respond_to?(:logp) && !record.logp.nil?
      tr
        td logP
        td= record.logp.to_f.smart_round_to_s
        td= bio_link_to_chemaxon :logp
    - if record.respond_to?(:alogps_logs) && !record.alogps_logs.nil?
      tr
        td logS
        td= record.alogps_logs.to_f.smart_round_to_s
        td= bio_link_to_source :alogps
    - if record.respond_to?(:pka_strongest_acidic) && !record.pka_strongest_acidic.nil?
      tr
        td pKa (Strongest Acidic)
        td= record.pka_strongest_acidic.to_f.smart_round_to_s
        td= bio_link_to_chemaxon :pka
    - if record.respond_to?(:pka_strongest_basic) && !record.pka_strongest_basic.nil?
      tr
        td pKa (Strongest Basic)
        td= record.pka_strongest_basic.to_f.smart_round_to_s
        td= bio_link_to_chemaxon :pka
    - if record.respond_to?(:physiological_charge) && !record.physiological_charge.nil?
      tr
        td Physiological Charge
        td= record.physiological_charge.to_f.smart_round_to_s
        td= bio_link_to_chemaxon :pka
    - if record.respond_to?(:acceptor_count) && !record.acceptor_count.nil?
      tr
        td Hydrogen Acceptor Count
        td= record.acceptor_count
        td= bio_link_to_chemaxon :ha_count
    - if record.respond_to?(:donor_count) && !record.donor_count.nil?
      tr
        td Hydrogen Donor Count
        td= record.donor_count
        td= bio_link_to_chemaxon :hd_count
    - if record.respond_to?(:polar_surface_area) && !record.polar_surface_area.nil?
      tr
        td Polar Surface Area
        td= record.polar_surface_area.to_f.smart_round_to_s + " Å²"
        td= bio_link_to_chemaxon :psa
    - if record.respond_to?(:rotatable_bond_count) && !record.rotatable_bond_count.nil?
      tr
        td Rotatable Bond Count
        td= record.rotatable_bond_count
        td= bio_link_to_chemaxon :rb_count
    - if record.respond_to?(:refractivity) && !record.refractivity.nil?
      tr
        td Refractivity
        td= record.refractivity.to_f.smart_round_to_s + " m³·mol⁻¹"
        td= bio_link_to_chemaxon :refractivity
    - if record.respond_to?(:polarizability) && !record.polarizability.nil?
      tr
        td Polarizability
        td= record.polarizability.to_f.smart_round_to_s + " Å³"
        td= bio_link_to_chemaxon :polarizability
    - if record.respond_to?(:number_of_rings) && !record.number_of_rings.nil?
      tr
        td Number of Rings
        td= record.number_of_rings
        td= bio_link_to_chemaxon :rb_count
    - if record.respond_to?(:bioavailability) && !record.bioavailability.nil?
      tr
        td Bioavailability
        td= record.bioavailability.to_f.smart_round_to_s
        td= bio_link_to_chemaxon :polarizability
    - if record.respond_to?(:rule_of_five) && !record.rule_of_five.nil?
      tr
        td Rule of Five
        td= human_boolean(record.rule_of_five)
        td= bio_link_to_chemaxon :polarizability
    - if record.respond_to?(:ghose_filter) && !record.ghose_filter.nil?
      tr
        td Ghose Filter
        td= human_boolean(record.ghose_filter)
        td= bio_link_to_chemaxon :polarizability
    - if record.respond_to?(:veber_rule) && !record.veber_rule.nil?
      tr
        td Veber's Rule
        td= human_boolean(record.veber_rule)
        td= bio_link_to_chemaxon :polarizability
    - if record.respond_to?(:mddr_like_rule) && !record.mddr_like_rule.nil?
      tr
        td MDDR-like Rule
        td= human_boolean(record.mddr_like_rule)
        td= bio_link_to_chemaxon :polarizability

app/views/compound/_protein_card.html.slim
.card
  .card-header
    = link_to "#{protein.header}".html_safe, protein_path(protein.id)
  .card-body
    div.container
      div.row
        div.col
          p
            | NCBI Accession Number: &nbsp;&nbsp;
            a href="https://www.ncbi.nlm.nih.gov/protein/#{protein.accession_no}" target="_blank" 
              = protein.accession_no
          p
            | Organism:&nbsp; #{protein.organism}
          p
            | Group:&nbsp; #{protein.group}
          p
            = link_to "More Infomation".html_safe, protein_path(protein.id)

app/views/compound/index.html.erb
<div class="container sequence-index">
	<h1>Compound Database</h1>
	<hr>
	<table id='compound-table'>
	  <thead>
	    <tr>
	      <th>RDDB ID</th>
	      <th>Name</th>
	      <th>Structure</th>
	      <!-- <th>Formula</th> -->
	      
	    </tr>

	    <tr>
	    <%= form_with url:'compound', method: :get do |f| %>
	      <th><%= f.submit "Filter", disabled: false, :id => 'filter-button' %></th>
	      <th><%= f.text_field 	:name %></th>
	      <th></th>
	      <th></th>
	    <% end %>
	      
	    </tr>
	  </thead>
	 	
	  <tbody>
	    <% @compound.each do |cp| %>
	      <tr>
	      	<!-- <%= cp.public_id %> -->
	        <td><%= link_to "#{cp.public_id}", compound_path(cp.id), :id => 'button-ish' %></td>
	        <td><%= cp.name %></td>
	        <% if cp.image.attached? %>
	        	<td><%= image_tag(cp.image) %></td>
	        <% else %>
	        	<td><%= image_tag("Photo-Not-Available-Image.jpg", :style => "width:130px;height:130px;") %></td>
	        <% end %>
	        
	      </tr>
	    <% end %>
	    
	  </tbody>
	</table>
	<hr>
	<%= paginate @compound %>
	<br>
</div>

app/views/compound/show.html.erb
<div class="container protein-info">

  <h2> Showing <%= @compound.name %> </h2>
  <%= render partial: 'compound/compound_show', locals: {:compound => @compound, :protein => @protein } %>

</div>