config/routes.rb
Rails.application.routes.draw do





	# static routes
	get 'statistics' => 'simple#statistics', as: :statistics
	get 'downloads' => 'simple#downloads', as: :downloads
	get 'contact'  => 'simple#contact', as: :contact
	get 'citation' => 'simple#citation', as: :cite
	get 'about' => 'simple#about', as: :about
	get 'other_database' => 'simple#other_database', as: :other_database
	get 'help' => 'simple#help', as: :help
	get 'home' => 'simple#home', as: :home


	# download route
	get "simple/download_aa_original"
	get "simple/download_nt_original"
	get "simple/download_aa_cus"
	get "simple/download_nt_cus"
	get "simple/download_entry_table_nt_orignal_docx"
	get "simple/download_entry_table_cus"
	get "query/download_new_fasta"
	get "protein/download_filtered_result"
	get "protein/download_filtered_result_fasta"



	match "search" => 'query#search',
		as: :search,
		via: [:get, :post]

	match "result" => 'query#result',
		as: :result,
		via: [:get, :post]

	match "phylogenetic_tree" => 'query#phylogenies',
		as: :phylogenetic_tree,
		via: [:post]

	match "submit_sequence" => "submit_sequence#submit",
		as: :submit_sequence,
		via: [:get, :post]

	match "phylogeny" => "phylogeny#show",
		as: :phylogeny,
		via: [:get, :post]


	resources :protein, only: [:show, :index] do
	end

	resources :compound, only: [:show, :index] do 
	end


	root to: 'simple#home'

end

app/controllers/protein_controller.rb
require 'csv'
require 'zip'
class ProteinController < ApplicationController
  # SortParamsParser is for sort_table_link
  include SortParamsParser
  include QueryLogic
  include SeqSummarizer
  helper ProteinHelper

  def download_filtered_result_fasta
    accession = params[:accession_no]
    header    = params[:header]
    group     = params[:group]
    organism  = params[:organism]
    # params.inspect => <ActionController::Parameters {"accession"=>"", "group"=>"", "header"=>"RS01800", "organism"=>"", "controller"=>"protein", "action"=>"download_filtered_result"} permitted: false>
    if !accession.present? and !header.present? and !group.present? and !organism.present?
      # no filter certiera given, sort by default (which is sort by group)
      @protein = CustomizedProteinSequence.all
      
    elsif accession.present? or header.present? or group.present? or organism.present?
      # filter certiera is given
      @protein = protein_index_just_filter(params,nil,true)

    end

    zip_file = package_fasta_for_filtered_result(@protein)
    send_file zip_file, :type => "application/zip", :filename =>  zip_file
  end


  def download_filtered_result
    accession = params[:accession_no]
    header    = params[:header]
    group     = params[:group]
    organism  = params[:organism]
    export_file_name = "tmp/filtered_result/filtered_result.csv" # user will see the name
    # params.inspect => <ActionController::Parameters {"accession"=>"", "group"=>"", "header"=>"RS01800", "organism"=>"", "controller"=>"protein", "action"=>"download_filtered_result"} permitted: false>
    if !accession.present? and !header.present? and !group.present? and !organism.present?
      # no filter certiera given, sort by default (which is sort by group)
      @protein = CustomizedProteinSequence.all
      
    elsif accession.present? or header.present? or group.present? or organism.present?
      # filter certiera is given
      @protein = protein_index_just_filter(params,nil,true)

    end

    filename = package_csv_for_filtered_result(@protein)
    send_file filename, :type => "application/csv", :filename =>  export_file_name
  end
	
  def index

  	if params[:commit] == "Filter"
      accession = params[:accession_no]
      header    = params[:header]
      group     = params[:group]
      organism  = params[:organism]
      genbank_id = params[:genbank_id]
      protein_name = params[:protein_name]
      # puts "params[:genbank_id] => #{params[:genbank_id]}"
      if params[:c].nil? and params[:d].nil?

        if accession.present? or header.present? or group.present? or organism.present? or genbank_id.present? or protein_name.present?
          @protein = protein_index_just_filter(params)
        else
          @protein = CustomizedProteinSequence.order(group: :ASC).limit(25).page(params[:page])
        end

      else
        # do filter and then sorting; if just sorting without filter at first, there is no params[:commit] 
        sort_order = nil
        if params[:d] == "up"
          sort_order = "asc"
        else
          sort_order = "desc"
        end

        if !accession.present? and !header.present? and !group.present? and !organism.present? and !genbank_id.present? and !protein_name.present?
          # no filter certiera given, sort by default (which is sort by group); this invoke when filter first, then sort second
          if params[:c] != "genbank_id"
            protein_sorted = CustomizedProteinSequence.order("customized_protein_sequences.#{params[:c]} is NULL, customized_protein_sequences.#{params[:c]} #{sort_order}").limit(25).page(params[:page])
          else
            protein_sorted = CustomizedProteinSequence.joins("left join customized_nucleotide_sequences on customized_nucleotide_sequences.protein_id = customized_protein_sequences.id")
                            .order("customized_nucleotide_sequences.accession_no is NULL, customized_nucleotide_sequences.accession_no #{sort_order}").limit(25).page(params[:page])
          end
          @protein = protein_sorted
          # @protein = CustomizedProteinSequence.order("customized_protein_sequences.#{params[:c]} is NULL, customized_protein_sequences.#{params[:c]} #{sort_order}").limit(25).page(params[:page])
          
        elsif accession.present? or header.present? or group.present? or organism.present? or genbank_id.present? or protein_name.present?

          @protein = protein_index_just_filter(params, sort=true)

        end

      end

    elsif !params[:commit].nil? and params[:commit] != "Filter"
      # this is 
      @protein = CustomizedProteinSequence.where(:group => params[:group]).limit(25).page(params[:page])
    
    else

      if params[:c].nil? and params[:d].nil?
        # https://stackoverflow.com/questions/5826210/rails-order-with-nulls-last
        @protein = CustomizedProteinSequence.order("customized_protein_sequences.group is NULL, customized_protein_sequences.group ASC").limit(25).page(params[:page])
      else
        # user did sorting without filter at first

        sort_order = nil
        protein_sorted = nil

        if params[:d] == "up"
          sort_order = "asc"
        else
          sort_order = "desc"
        end

        if params[:commit].nil?
          if params[:c] != "genbank_id"
            protein_sorted = CustomizedProteinSequence.order("customized_protein_sequences.#{params[:c]} is NULL, customized_protein_sequences.#{params[:c]} #{sort_order}").limit(25).page(params[:page])
          else
            protein_sorted = CustomizedProteinSequence.joins("left join customized_nucleotide_sequences on customized_nucleotide_sequences.protein_id = customized_protein_sequences.id")
                            .order("customized_nucleotide_sequences.accession_no is NULL, customized_nucleotide_sequences.accession_no #{sort_order}").limit(25).page(params[:page])
          end
          @protein = protein_sorted
        end

      end
    end
    
  end




  def show
    @protein_s = CustomizedProteinSequence.find(params[:id])
    @member = Array.new
    group_members = CustomizedProteinSequence.where(:group => @protein_s.group)

    group_members.each do |m|
      if m.header != @protein_s.header
        @member << m
      end
    end

    @gene_s = CustomizedNucleotideSequence.find_by(:protein_id => @protein_s.id)

    @compound = Array.new
    associated_compound = CompoundStrainRel.where(:protein_id => @protein_s.id)
    associated_compound.each do |comp|
      @compound << Compound.find(comp.compound_id)
    end
    
    @reference = Reference.where(:strain_id => @protein_s.id)
    @mw = calculateMolecularWeight(@protein_s.chain)
    
  end
end

app/helpers/protein_helper.rb
module ProteinHelper


	def contain_compound(protein_id)
		rel = CompoundStrainRel.where(:protein_id => protein_id)
		if rel.length > 0
			return true
		else
			return false
		end
	end

	def style_chain(chain)
		after_style = ""
		length_per_line = 60 # 60 char then \n
		space_per_line = 10 # 10 char then space
		# {line number}<span></span>
		after_style += "1 <span>"
		(1..chain.length).step(1) do |n|
			
			if n%space_per_line == 0
				after_style += " "
			end

			if n%length_per_line == 0
				# new line
				after_style +=  "</span><br>#{n+1} <span>"
			end
			after_style += chain[n-1]
		end

		after_style += "</span>"

		# convert string to html element
		return after_style.html_safe
	end


	def get_genbank_id(protein_id)
		gene = CustomizedNucleotideSequence.find_by(:protein_id => protein_id)
		
		return gene.accession_no
	end

	def get_reference(protein_id)
		reference = Reference.find_by(:strain_id => protein_id)
		pubmed_id = nil
		if !reference.nil?
			pubmed_id = reference.pubmed_id
		end
		return pubmed_id
		
	end

	def itatic_species_genus(organism)
		species = ["Dehalococcoides", "mccartyi",
							"Anaeromyxobacter","dehalogenans",
							"Desulfitobacterium", "sp.",
							"Dehalobacter",
							"Sulfurospirillum", "multivorans",
							"Desulfitobacterium", "dehalogenans",
							"Dehalobacterium", "halfniense",
							"Dehalobacter", "restrictus",
							"Desulfitobacterium", "dichloroeliminans",
							"Dehalogenimonas",
							"Desulfitobacterium", "hafniense",
							"Sulfurospirillum", "halorespirans",
							"Clostridium", "difficile",
							"Geobacter", "lovleyi", "lykanthroporepellens"]

		name_array = organism.split(" ")
		if name_array.length == 1
			itatic_string = "<i>#{name_array[0]}</i>"
			return itatic_string.html_safe
		elsif name_array.length > 1
			itatic_string = ""
			name_array.each do |name_|
				if species.include? name_
					itatic_string += "<i>#{name_}</i> "
				else
					itatic_string += "#{name_} "
				end
			end
			itatic_string[itatic_string.length - 1] = ""
			return itatic_string.html_safe
		end

	end


end

app/views/protein/_compound_card.html.slim
.card
  .card-header
    = link_to "#{compound.name}".html_safe, compound
  .card-body
    div.container
      div.row
        div.col-4
          - if compound.image.attached?
            = image_tag(compound.image)
          - else
            = image_tag("Photo-Not-Available-Image.jpg", :style => "width:130px;height:130px;")
        div.col-8
          p
            | Compound Name: #{compound.name}
          p
            | Compound Formula: #{compound.formula}
          p
            | Average Mass: #{compound.average_mass}
          p
            = link_to "More Infomation".html_safe, compound

app/views/protein/index.html.erb
<div class="container sequence-index">
	<h1>Sequence Database</h1>
	<hr>
	<table id='strain-table'>

	  <thead>
	    <tr>
	      <th colspan="1"></th>
	      <!-- this is how btdb sort protein by BTDBP ID -->
	      <!-- <a rel="nofollow" class="sort-link" href="/proteins?c=btdbp_id&amp;d=down">BTDBP ID</a> -->
	      <%# table_sort_link 'Locus Tag', :header %>
	      <th><%= table_sort_link "AccessionID", :accession_no %></th>
	      <th><%= table_sort_link "Name", :header %></th>
	      <th><%= table_sort_link "GeneBankID", :genbank_id %></th>
	      <th><%= table_sort_link "Group", :group %></th>
	      <th><%= table_sort_link "Organism", :organism %></th>
	      <th><%= table_sort_link "Protein", :protein_name %></th>
	      <th>Reference</th>
	      
	    </tr>

	    <tr>
	    <%= form_with url:'protein', method: :get do |f| %>
	      <th><%= f.submit "Filter", disabled: false, :id => 'filter-button' %></th>
	      <th><%= f.text_field 	:accession_no, :style => "width:140px"%></th>
	      <th><%= f.text_field 	:header %></th>
	      <th><%= f.text_field  :genbank_id %></th>
	      <th><%= f.text_field  :group, :style => "width:60px"%></th>
	      <th><%= f.text_field  :organism %></th>
	      <th><%= f.text_field  :protein_name, :style => "width:70px" %></th>
	      <th><%= f.text_field  :fake, :disabled => true, :placeholder => "N/A", :style => "width:100px" %></th> 
	      <!-- :fake means nothing, just for styling -->
	    <% end %>
	      
	    </tr>
	  </thead>
	 	
	  <tbody>
	    <% @protein.each do |pt| %>
	      <tr>
	      	<td><%= link_to "show", protein_path(pt.id), :id => 'show-button' %></td>

	      	<% if pt.accession_no.nil? %>
	      		<td>Not Available</td>
	      	<% else %>
	      		<td><a href="https://www.ncbi.nlm.nih.gov/protein/<%= pt.accession_no %>" target="_blank">
	      			<%= pt.accession_no %>
	      		</td>
	      	<% end %>
	        


	        <td><%= pt.header %></td>


	        <td>

	        	<% if get_genbank_id(pt.id).nil? %>
	        		None
	        	<% else %>
	        		<%= link_to get_genbank_id(pt.id), "https://www.ncbi.nlm.nih.gov/nuccore/#{get_genbank_id(pt.id)}" %>
	        	<% end %>


	        </td>

	        <!-- display group -->
	        <% if pt.group.nil? %>
	        	<td>No Group</td>
	        <% else %>
	        	<%= form_with url:'protein', method: :get do |f| %>
	        		<%= hidden_field_tag(:group, pt.group) %>
	        		<td><%= f.submit "#{pt.group}", disabled: false, :id => 'group-click-button' %></td>
	        	<% end %>
	        <% end %>

	        <!-- display organism -->
	        <% if pt.organism.nil? %>
	        	<td>No Organism</td>
	        <% else %>
	        	<td><%= itatic_species_genus(pt.organism) %></td>
	        <% end %>
	        

	        <% if pt.protein_name.nil? %>
	        	<td style="text-align: center;">None</td>
	        <% else %>
	        	<td style="color:red; text-align: center;"><strong><%=  pt.protein_name %></strong></td>
	        <% end %>
	        	
	        	
	        <!-- display characteristics -->
	        <td style="text-align: right;">
	        	<% if get_reference(pt.id).nil? %>
		        	Unpublished
		        <% else %>
		        	
		        	<%= link_to get_reference(pt.id), "https://www.ncbi.nlm.nih.gov/pubmed/#{get_reference(pt.id)}" %>
		        <% end %>

		        <%# link_to get_reference(pt.id), "https://www.ncbi.nlm.nih.gov/pubmed/#{get_reference(pt.id)}" %>
	    	</td>
	        
	      </tr>
	    <% end %>
	    
	  </tbody>
	</table>
	<%= link_to "Export As CSV", protein_download_filtered_result_path(:accession_no => params[:accession_no],:header => params[:header], :group => params[:group], :organism => params[:organism]), :id => "export-button" %>
	<%= link_to "Export As Fasta", protein_download_filtered_result_fasta_path(:accession_no => params[:accession_no],:header => params[:header], :group => params[:group], :organism => params[:organism]), :id => "export-button" %>
	<hr>
	<%= paginate @protein %>
	<br>
</div>

app/views/protein/show.html.erb
<div class="container protein-info">

<% if @protein_s.header != "None" %>
  <h2>Showing Protein Sequence: <%= @protein_s.header %></h2>
<% else %>
  <h2>Showing Protein Sequence: <%= @protein_s.accession_no %></h2>
<% end %>


<hr>
<h4>Identification</h4>
<div id = "tablediv">
  <table>
    <tr>
      <th>Common Name</th>
      <td><%= @protein_s.header %></td>
    </tr>
    <tr>
      <th>Orthologous Group</th>
      <td>
        <%= form_with url:'/protein', method: :get do |f| %>
          <%= hidden_field_tag(:group, @protein_s.group) %>
          <%= f.submit "#{@protein_s.group}", disabled: false, :id => 'group-click-button' %>
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Organism</th>
      <th><%= @protein_s.organism || nil %></th>
    </tr>

    <tr>
      <th>Protein Name</th>
      <td><%= @protein_s.protein_name || "Un-Characterized" %></td>
    </tr>

    

    <tr>
      <th> Submitter </th>
      <% if @protein_s.uploader == "RDDB" %>
        <td>Reductive Dehalogenases Database</td>
      <% else %>
        <td><%= @protein_s.uploader_name %>. Email: <%= @protein_s.uploader_email %></td>
      <% end %>
    </tr>

    <tr>
      <th>Reference </th>
      <td>
        <% if @reference.length != 0 %>
          <% @reference.each do |ref| %>
            <a href="https://www.ncbi.nlm.nih.gov/pubmed/<%= ref.pubmed_id %>" target="_blank"> <%= ref.pubmed_id %>
          <% end %>
        <% else %>
          Unpublished
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Last Updated </th>
      <td><%= @protein_s.updated_at || nil %></td>
    </tr>

  </table>
</div>

<hr>
<div>
  <h4>Protein Properties</h4>
  <% if @protein_s.chain.present? %>
    <!-- Button for quick view of the sequence -->
    <button class="little-button" onclick="writeFASTA('<%= @protein_s.chain %>', 
                          '<%= @protein_s.header %>','<%= @protein_s.accession_no %>', '<%= @protein_s.organism %>')">FASTA</button>
    <button class="little-button" onclick="writeSequenceStats('<%= @protein_s.chain %>','aa')">Statistics</button>
    <!-- Button for quick view of the sequence -->
    <div id = "tablediv">
      <table>
        <tr>
          <th>Amino Acid Sequence</th>
          <td>
            <em class="sequence-wrap" ><%= style_chain(@protein_s.chain) %></em>
            <%= content_tag :div, class: "protein_s_chain", data: {proteinChain: @protein_s.chain} do %>
            <% end %>
          </td>
        </tr> 
        <tr>
          <th>Sequence Length</th>
          <td><%= @protein_s.chain.length %></td>
        </tr> 
        <tr>
          <th>Molecular Weight</th>
          <td><%= @mw %> kDa</td>
        </tr>
        <tr>
          <th>Predicted PI (EMBOSS)</th>
          <td id="ppi-emboss"></td>
        </tr>
        <tr>
          <th>Accession Number</th>
          <td><a href="https://www.ncbi.nlm.nih.gov/protein/<%= @protein_s.accession_no %>" target="_blank"> <%= @protein_s.accession_no %></td>
        </tr>
      </table>
    </div>

  <% else %>
    <div id = "tablediv">
      <table>
        <tr>
          <th>Amino Acid Sequence</th>
          <td>
            <%= nah %>
          </td>
        </tr>
      </table>
    </div>
  <% end %>
</div>

<hr>
<div>
  <h4>Gene Properties</h4>
  <% if !@gene_s.nil? and @gene_s.chain.present? %>
    <!-- Button for quick view of the sequence -->
    <button class="little-button" onclick="writeFASTA('<%= @gene_s.chain %>', 
                          '<%= @protein_s.header %>',undefined, '<%= @protein_s.organism %>')">FASTA</button>
    <button class="little-button" onclick="writeSequenceStats('<%= @gene_s.chain %>','nt')">Statistics</button>
    <!-- Button for quick view of the sequence -->
    <div id = "tablediv">
      <table>
        <tr>
          <th>Nucleotide Sequence</th>
          <td>
            <em class="sequence-wrap" ><%= style_chain(@gene_s.chain) %></em>
            <%= content_tag :div, class: "gene_s_chain", data: {geneChain: @gene_s.chain} do %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>Molecular Weight</th>
          <td id="gene-pmw"></td>
        </tr>
        <tr>
          <th>NCBI GeneBank ID</th>
          <th id="gene-pmw">
            <a href="https://www.ncbi.nlm.nih.gov/nuccore/<%= @gene_s.accession_no %>" target="_blank"> <%= @gene_s.accession_no %></th>
        </tr>
      </table>
    </div>

  <% else %>

    <div id = "tablediv">
      <table>
        <tr>
          <th>Nucleotide Sequence</th>
          <td>
            <%= nah %>
          </td>
        </tr>
      </table>
    </div>
    
  <% end %>
</div>

<hr>
<h4>Interactive Compounds</h4>
<div id = "tablediv">
  <div class="well-panel">
    <% if @compound.length > 0 %>

      <% @compound.each do |comp| %>
        <%= render :partial => 'compound_card', :locals => { :compound => comp} %>
      <% end %>

    <% else %>
      <p> This strain doesn't have any associated compounds </p>
    <% end %>
  </div>
</div>


</div>